language: generic
sudo: required
services: 
  -  docker

before_install:
  - docker build -t apel73/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true apel73/react-test npm run test -- --coverage

after_success:
  - docker build -t apel73/multi-client ./client
  - docker build -t apel73/multi-nginx ./nginx
  - docker build -t apel73/multi-server ./server
  - docker build -t apel73/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push apel73/multi-client
  - docker push apel73/multi-nginx
  - docker push apel73/multi-server
  - docker push apel73/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-506086818725
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"